kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wordpress
subjects:
- kind: ServiceAccount
  name: wordpress
roleRef:
  kind: Role
  name: wordpress
  apiGroup: rbac.authorization.k8s.io
